spring:
  application:
    name: zuul-service
server:
  port: 8073
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
zuul:
  prefix: /api
  routes:
    hello-server:
      path: /server/**
      serviceId : hello-server-eureka-example
    hello-client:
      path: /client/**
      serviceId: hello-client-eureka-example
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000